services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ndesprez
      POSTGRES_PASSWORD: msp
      POSTGRES_DB: piscineds
    expose:
      - 5432
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres
      volumes:
        - "./pgadmin/var/lib/pgadmin:/var/lib/pgadmin"

# docker-compose up -d
# chmod -R 777 ./pgadmin/var/lib/pgadmin
# docker-compose down