services:
  postgres:
    image: postgres:15
    container_name: piscineds_postgres
    environment:
      POSTGRES_USER: ndesprez
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

# docker-compose up
# docker exec -it piscineds_postgres bash
# psql -U ndesprez -d piscineds -h localhost -W
# ...
# docker-compose down
# docker system prune -af
